Repository IkramKhan-DevOps/saifgrp-services-app, pull requests merged in 2023-07, with the labels that each got.

#5 check point: Before code marge and resolved some issues and added ref…
  lib/data/networks/network_api_services.dart
  lib/main.dart
  lib/resources/assets/app_image.dart
  lib/resources/routes/routes.dart
  lib/view_models/controller/forget_password_controller/forget_password_controller.dart
  lib/view_models/controller/login controller/login_screen_controller.dart
  lib/view_models/controller/register_screen_controller/register_screen_controller.dart
  lib/view_models/controller/request_controller/request_controller.dart
  lib/view_models/controller/request_controller/request_history_controller.dart
  lib/view_models/controller/update_profile_controller/update_profile_controller.dart
  lib/views/auth/update_profile_screen.dart
  lib/views/home_screens/Request/request_screen.dart
  lib/views/home_screens/drawer_screen/complaint_screen.dart
  lib/views/home_screens/drawer_screen/request_history_screen.dart
  lib/views/home_screens/home_main_screen.dart
  lib/views/home_screens/home_screen.dart
  lib/views/home_screens/services.dart
Labels: bug, enhancement

#6 check point: Redesign the home page
  lib/main.dart
  lib/views/home_screens/home_screen.dart
  lib/views/home_screens/resedent.dart
Labels: enhancement

#7 App is Finilize and Resolved all issues and updated some designing areas
  lib/main.dart
  lib/utils/utils.dart
  lib/view_models/controller/login controller/login_screen_controller.dart
  lib/view_models/controller/register_screen_controller/register_screen_controller.dart
  lib/view_models/controller/request_controller/request_history_controller.dart
  lib/views/home_screens/drawer_screen/request_history_screen.dart
  lib/views/home_screens/home_main_screen.dart
  lib/views/home_screens/home_screen.dart
  lib/views/home_screens/services.dart
Labels: bug, enhancement

#9 Fix,Changes from Rizwan
  lib/data/app_exceptions.dart
  lib/data/networks/network_api_services.dart
  lib/view_model/controller/login controller/login_screen_controller.dart
  lib/view_model/controller/register_screen_controller/register_screen_controller.dart
  lib/view_model/controller/request_controller/request_controller.dart
  lib/view_model/controller/service_history_controller/service_history_controller.dart
  lib/view_model/controller/update_profile_controller/update_profile_controller.dart
  lib/view_model/controller/user_session_controller/store_user_data.dart
  lib/views/auth_screen/register_screen.dart
Labels: bug, documentation, duplicate

#10 forgot password +design changes
  lib/utils/utils.dart
  lib/view_model/controller/all_services_controller/all_services_controller.dart
  lib/view_model/controller/change_password_controller/change_password_controller.dart
  lib/view_model/controller/login controller/login_screen_controller.dart
  lib/view_model/controller/register_screen_controller/register_screen_controller.dart
  lib/view_model/controller/request_controller/request_controller.dart
  lib/view_model/controller/service_history_controller/service_history_controller.dart
  lib/view_model/controller/update_profile_controller/update_profile_controller.dart
  lib/view_model/controller/user_session_controller/store_user_data.dart
  lib/views/auth_screen/auth_main_screen.dart
  lib/views/auth_screen/login_screen.dart
  lib/views/auth_screen/register_screen.dart
  lib/views/home_main_screen.dart
  lib/views/home_screens/profile_screen/change_password_screen.dart
  lib/views/home_screens/profile_screen/profile_screen.dart
  lib/views/home_screens/service_history_screen/service_history_component/service_history_container.dart
  lib/views/home_screens/service_history_screen/service_history_screen.dart.dart
  lib/views/home_screens/service_screens/service_screen_component/service_screen_container.dart
  lib/views/splash_screen.dart
  lib/views/welcome_screen.dart
Labels: enhancement

#19 Update the changes : password icons issues are solves+terminal prob are 0+change password show icon is added+login 2 text feilds distance are fixed
  lib/data/app_exceptions.dart
  lib/data/networks/network_api_services.dart
  lib/models/complaint_model.dart
  lib/models/profile_update_model.dart
  lib/repository/all_services_repository/all_services_repository.dart
  lib/repository/change_password_repository/change_password_repository.dart
  lib/repository/forget_password_repository/forget_passsword_repository.dart
  lib/repository/register_repository/register_repository.dart
  lib/utils/routes/routes.dart
  lib/view_model/controller/all_services_controller/all_services_controller.dart
  lib/view_model/controller/building_controller/building_controller.dart
  lib/view_model/controller/forget_password_controller/forget_password_controller.dart
  lib/view_model/controller/login controller/login_screen_controller.dart
  lib/view_model/controller/register_screen_controller/register_screen_controller.dart
  lib/view_model/controller/update_profile_controller/update_profile_controller.dart
  lib/views/auth_screen/auth_main_screen.dart
  lib/views/auth_screen/login_screen.dart
  lib/views/auth_screen/register_screen.dart
  lib/views/home_main_screen.dart
  lib/views/home_screens/profile_screen/change_password_screen.dart
  lib/views/home_screens/service_screens/allServicesScreen.dart
  lib/views/home_screens/service_screens/complaintFormScreen.dart
  lib/views/splash_screen.dart
Labels: bug, enhancement
